spring:
  application:
    name: okta-test

server:
  port: 8099


auth0:
  toyota:
    domain: "toyota-kr-test.us.auth0.com"
    client-id: "Edwip0uwJvMZaZTDYlGqQl7S815AuZQK"
    redirect-uri: "http://localhost:8099/?mode=toyota"
    audience: "https://24dcm-dev-tmcif.tmkr-connected.com"
  lexus:
    domain: "lexus-kr-test.us.auth0.com"
    client-id: "xKrsdYuvlq4sSvZAy6LB1RKF9EZSx6tB"
    redirect-uri: "http://localhost:8099/?mode=lexus"
    audience: "https://24dcm-dev-tmcif.tmkr-connected.com"
