spring:
  application:
    name: okta-test

server:
  port: 8090


auth0:
  toyota:
    domain: "toyota-kr-dev.jp.auth0.com"
    client-id: "2ZLCaqHKeNXqzqDHHxcq5mPAGdA7cbzU"
    redirect-uri: "http://10.28.3.180:8090/?mode=toyota"
    audience: "https://24dcm-dev-tmcif.tmkr-connected.com"
  lexus:
    domain: "lexus-kr-dev.jp.auth0.com"
    client-id: "Fn0xeEDTGVebPtbqfEJQ8l1m2HTkQHjS"
    redirect-uri: "http://10.28.3.180:8090/?mode=lexus"
    audience: "https://24dcm-dev-tmcif.tmkr-connected.com"
