spring:
  application:
    name: okta-test

server:
  port: 8090


okta:
  oauth2:
    issuer: "https://dev-gpbeh1okvt78qecy.us.auth0.com/"
    client-id: "ENC(51g/CSqmsq98Mlh46puMy3/0MqdEl/irPDrgTcdP15zaVMfEV1n4a+qFS/3rbiqy)"
    client-secret: "ENC(BZaQgeqfvf/w5GmYc0Ra+cM95x4vKQCYOId3ERkfWwQ/YCPDKph1h4JULyFZ9D9Dn5Gn3/AHHgG4IFWM4ZER0d/gACn99sKwzX1nz7J12Qs=)"
