spring:
  application:
    name: okta-test

server:
  port: 8098
  servlet:
    context-path: auth0-test


auth0:
  toyota:
    domain: "auth-dev.toyotaconnectapp.com"
    client-id: "2ZLCaqHKeNXqzqDHHxcq5mPAGdA7cbzU"
    redirect-uri: "https://evcar-tms.obigo.com/auth0-test?mode=toyota"
    audience: "https://24dcm-dev-tmcif.tmkr-connected.com"
  lexus:
    domain: "auth-dev.lexusconnectapp.com"
    client-id: "Fn0xeEDTGVebPtbqfEJQ8l1m2HTkQHjS"
    redirect-uri: "https://evcar-tms.obigo.com/auth0-test?mode=lexus"
    audience: "https://24dcm-dev-tmcif.tmkr-connected.com"
