spring:
  application:
    name: okta-test

server:
  port: 80


okta:
  oauth2:
    issuer: "https://lguplus.okta.com"
    client-id: "0oacctv964uu213O2697"
    client-secret: "zk7QXgKQJHoHi2Cn4GbnwgazOA4ErukRZDfkNknyhT7trBmszVNxBOFpeAJ1rNCl"
    redirect-uri: "http://manager.dmtv.upluscar.co.kr/manager/oauth2/okta/redirect"
