spring:
  application:
    name: okta-test

server:
  port: 8099


auth0:
  toyota:
    domain: "auth-dev.toyotaconnectapp.com"
    client-id: "2ZLCaqHKeNXqzqDHHxcq5mPAGdA7cbzU"
    redirect-uri: "https://evcar-tms.obigo.com/?mode=toyota"
    audience: "https://24dcm-tmcif.tmkr-connected.com"
  lexus:
    domain: "auth-dev.lexusconnectapp.com"
    client-id: "Fn0xeEDTGVebPtbqfEJQ8l1m2HTkQHjS"
    redirect-uri: "https://evcar-tms.obigo.com/?mode=lexus"
    audience: "https://24dcm-tmcif.tmkr-connected.com"

  toyota-stg:
    domain: "auth-sta.toyotaconnectapp.com"
    client-id: "EIB0Gqq2O48tmJzOZBQu2hrtMwney1Vf"
    redirect-uri: "https://evcar-tms.obigo.com/stg?mode=toyota"
    audience: "https://24dcm-tmcif.tmkr-connected.com"
  lexus-stg:
    domain: "auth-sta.lexusconnectapp.com"
    client-id: "LHVuUPFXvy9FWS7Mh0iaBPdMcsuCrwRw"
    redirect-uri: "https://evcar-tms.obigo.com/stg?mode=lexus"
    audience: "https://24dcm-tmcif.tmkr-connected.com"

  toyota-prod:
    domain: "toyota-kr.jp.auth0.com"
    client-id: "auLv9ZgWcykoQ676jUPnOJh66i1SW4cy"
    redirect-uri: "https://evcar-tms.obigo.com/prod?mode=toyota"
    audience: "https://24dcm-tmcif.tmkr-connected.com"
  lexus-prod:
    domain: "lexus-kr.jp.auth0.com"
    client-id: "vw3jni0EErELvg35B4cRsSxKS3so3rBH"
    redirect-uri: "https://evcar-tms.obigo.com/prod?mode=lexus"
    audience: "https://24dcm-tmcif.tmkr-connected.com"
