spring:
  application:
    name: okta-test

server:
  port: 8099


auth0:
  toyota:
    domain: "auth-dev.toyotaconnectapp.com"
    client-id: "2ZLCaqHKeNXqzqDHHxcq5mPAGdA7cbzU"
    redirect-uri: "http://localhost:8099/?mode=toyota"
    audience: "https://24dcm-tmcif.tmkr-connected.com"
  lexus:
    domain: "auth-dev.lexusconnectapp.com"
    client-id: "Fn0xeEDTGVebPtbqfEJQ8l1m2HTkQHjS"
    redirect-uri: "http://localhost:8099/?mode=lexus"
    audience: "https://24dcm-tmcif.tmkr-connected.com"

  toyota-stg:
    domain: "auth-sta.toyotaconnectapp.com"
    client-id: "EIB0Gqq2O48tmJzOZBQu2hrtMwney1Vf"
    redirect-uri: "http://localhost:8099/stg?mode=toyota"
    audience: "https://24dcm-tmcif.tmkr-connected.com"
  lexus-stg:
    domain: "auth-sta.lexusconnectapp.com"
    client-id: "LHVuUPFXvy9FWS7Mh0iaBPdMcsuCrwRw"
    redirect-uri: "http://localhost:8099/stg?mode=lexus"
    audience: "https://24dcm-tmcif.tmkr-connected.com"
